//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "userdetails")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub user_id: i32,
    pub username: Option<String>,
    pub first_name: String,
    pub last_name: String,
    pub location: String,
    pub police_station: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
